name: Deploy to Cloud Run
description: Deploy a specific image tag to Cloud Run (Terraform manages all configuration)

inputs:
  environment:
    description: 'Environment to deploy (staging, candidate, production)'
    required: true
  image_tag:
    description: 'Image tag to deploy'
    required: true
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Get infrastructure config from Terraform
      shell: bash
      run: |
        # Clone infrastructure repo to read Terraform outputs
        # (In production, you'd use a shared artifact or API)
        git clone --depth 1 https://github.com/${{ github.repository_owner }}/bridge_backend_infra /tmp/infra || true

        cd /tmp/infra/terragrunt || {
          echo "âš ï¸ Infrastructure repo not available, using hardcoded fallback config"
          # Fallback: Use hardcoded values (should match Terraform configuration)
          echo "PROJECT_ID=bridge-477812" >> $GITHUB_ENV
          echo "REGION=asia-south1" >> $GITHUB_ENV
          echo "REGISTRY_URL=asia-south1-docker.pkg.dev/bridge-477812/bridge-repo/bridge-api" >> $GITHUB_ENV

          # Service names (canonical from Terraform)
          case "${{ inputs.environment }}" in
            dev) echo "SERVICE_NAME=bridge-api-dev" >> $GITHUB_ENV ;;
            staging) echo "SERVICE_NAME=bridge-api-staging" >> $GITHUB_ENV ;;
            production) echo "SERVICE_NAME=bridge-api-production" >> $GITHUB_ENV ;;
          esac
          exit 0
        }

        # Query Terraform for canonical infrastructure values
        ./terragrunt.exe output -json --terragrunt-working-dir=live/cicd-config > /tmp/tf_outputs.json || {
          echo "âš ï¸ Terragrunt output failed, using environment-based naming"
          echo "PROJECT_ID=bridge-477812" >> $GITHUB_ENV
          echo "REGION=asia-south1" >> $GITHUB_ENV
          echo "REGISTRY_URL=asia-south1-docker.pkg.dev/bridge-477812/bridge-repo/bridge-api" >> $GITHUB_ENV

          case "${{ inputs.environment }}" in
            dev) echo "SERVICE_NAME=bridge-api-dev" >> $GITHUB_ENV ;;
            staging) echo "SERVICE_NAME=bridge-api-staging" >> $GITHUB_ENV ;;
            production) echo "SERVICE_NAME=bridge-api-production" >> $GITHUB_ENV ;;
          esac
          exit 0
        }

        # Extract values from Terraform outputs (canonical source)
        PROJECT_ID=$(jq -r '.project_id.value' /tmp/tf_outputs.json)
        REGION=$(jq -r '.region.value' /tmp/tf_outputs.json)
        REGISTRY_URL=$(jq -r '.registry_url.value' /tmp/tf_outputs.json)
        SERVICE_NAME=$(jq -r ".service_${{ inputs.environment }}.value" /tmp/tf_outputs.json)

        echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
        echo "REGION=$REGION" >> $GITHUB_ENV
        echo "REGISTRY_URL=$REGISTRY_URL" >> $GITHUB_ENV
        echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV

    - name: Deploy to Cloud Run
      shell: bash
      run: |
        echo "ðŸš€ Deploying to ${{ inputs.environment }}..."
        echo "ðŸ“¦ Image: ${REGISTRY_URL}:${{ inputs.image_tag }}"
        echo "ðŸŽ¯ Service: ${SERVICE_NAME}"
        echo "ðŸ“ Git SHA: ${{ github.sha }}"

        # Prepare traceability metadata
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        DEPLOYED_AT=$(date +%s)

        # Deploy with full traceability metadata (Fortune 500 pattern)
        # Terraform controls infrastructure, CI/CD adds deployment metadata
        gcloud run deploy ${SERVICE_NAME} \
          --image=${REGISTRY_URL}:${{ inputs.image_tag }} \
          --region=${REGION} \
          --platform=managed \
          --update-labels=git-sha=${SHORT_SHA},deployed-at=${DEPLOYED_AT},env=${{ inputs.environment }} \
          --update-annotations=git-commit=${{ github.sha }},git-branch=${{ github.ref_name }},deployed-by=github-actions \
          --quiet

        # Get service URL
        SERVICE_URL=$(gcloud run services describe ${SERVICE_NAME} --region=${REGION} --format='value(status.url)')

        echo "## âœ… Deployment Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ inputs.image_tag }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Service:** ${SERVICE_NAME}" >> $GITHUB_STEP_SUMMARY
        echo "**URL:** $SERVICE_URL" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ“ Traceability" >> $GITHUB_STEP_SUMMARY
        echo "**Git Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Git Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Short SHA:** \`${SHORT_SHA}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Deployed At:** ${DEPLOYED_AT} (Unix timestamp)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "ðŸŽ‰ Infrastructure values from Terraform (canonical), deployment by CI/CD!" >> $GITHUB_STEP_SUMMARY

        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
