# Generated by Django 5.2.7 on 2025-11-10 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="e.g., LI-2025-123", max_length=50, unique=True
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(help_text="For quick reference", max_length=200),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "form_data",
                    models.JSONField(
                        help_text="Complete form submission data (flexible structure)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="mobile_app",
                        help_text="mobile_app, web, referral",
                        max_length=50,
                    ),
                ),
                ("referral_code", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_progress", "In Progress"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="accounts.agent",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user assigned to process this lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "leads_lead",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Lead Created"),
                            ("status_change", "Status Changed"),
                            ("note_added", "Note Added"),
                            ("document_uploaded", "Document Uploaded"),
                            ("assigned", "Assigned to User"),
                            ("contacted", "Customer Contacted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="leads.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Activity",
                "verbose_name_plural": "Lead Activities",
                "db_table": "leads_leadactivity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_proof", "ID Proof"),
                            ("address_proof", "Address Proof"),
                            ("income_proof", "Income Proof"),
                            ("medical_report", "Medical Report"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="lead_documents/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Document",
                "verbose_name_plural": "Lead Documents",
                "db_table": "leads_leaddocument",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["reference_number"], name="leads_lead_referen_a5dfce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["agent", "status"], name="leads_lead_agent_i_69cbdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "created_at"], name="leads_lead_status_2b0e1e_idx"
            ),
        ),
    ]
