# Generated by Django 5.2.7 on 2025-11-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("leads", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for public share submissions",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="accounts.agent",
            ),
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Life Insurance Application Form'",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Instructions for filling the form"
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        help_text="Form field definitions (JSON structure)"
                    ),
                ),
                (
                    "is_shareable",
                    models.BooleanField(
                        default=False,
                        help_text="Can this form be shared via public link?",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        help_text="Unique token for public access (e.g., /forms/share/abc123xyz)",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "share_expiry",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiry for share link",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this form is for a specific product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_templates",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Template",
                "verbose_name_plural": "Form Templates",
                "db_table": "leads_formtemplate",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="form_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The form template used (if dynamic form)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="leads.formtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(
                fields=["share_token"], name="leads_formt_share_t_a59bb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(
                fields=["product", "is_active"], name="leads_formt_product_e3adc9_idx"
            ),
        ),
    ]
