# Generated by Django 5.2.7 on 2025-11-14 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_lead_agent_formtemplate_lead_form_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Primary unique identifier - phone number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Email address (optional, can change)",
                        max_length=254,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Customer name (can change)", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "leads_client",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["phone"], name="leads_clien_phone_7434b5_idx"),
                    models.Index(fields=["email"], name="leads_clien_email_0ecfe7_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client who submitted this lead (Google-style immutable ID)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="leads.client",
            ),
        ),
    ]
