# Generated by Django 5.2.7 on 2025-11-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_client_lead_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Auto-generated PDF of lead form (created on submission)",
                null=True,
                upload_to="lead_pdfs/%Y/%m/",
            ),
        ),
    ]
