# Generated by Django 5.2.7 on 2025-11-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Insurance, Loans", max_length=100
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name for Flutter", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Main Category",
                "verbose_name_plural": "Main Categories",
                "db_table": "products_maincategory",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Life Insurance, Car Insurance", max_length=100
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name for Flutter", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "form_template",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default form fields for products in this sub-category",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="products.maincategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
                "db_table": "products_subcategory",
                "ordering": ["main_category", "display_order", "name"],
                "unique_together": {("main_category", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Term Life Plan, Home Loan Premium",
                        max_length=200,
                    ),
                ),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "key_features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key features/benefits",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("flat", "Flat Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom product info (provider, terms, etc.)",
                    ),
                ),
                (
                    "custom_form_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Override sub-category form template",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products_product",
                "ordering": ["sub_category", "name"],
                "unique_together": {("sub_category", "slug")},
            },
        ),
    ]
