name: Run Security Scan
description: Run Trivy security scan on Docker image

inputs:
  image_name:
    description: 'Docker image name to scan'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image (cached)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: ${{ inputs.image_name }}:security-scan
        cache-from: type=gha

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image_name }}:security-scan
