name: Run Quality Checks
description: Run linting and type checking (ruff + mypy)

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'

    - name: Export DJANGO env for mypy
      shell: bash
      run: |
        echo "DJANGO_ENV=ci" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=bridge_backend.settings" >> $GITHUB_ENV
        echo "PYTHONPATH=${{ github.workspace }}/app" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff mypy django-stubs

    - name: Run linters and mypy
      shell: bash
      run: |
        cd app
        ruff check . || true
        mypy . --no-incremental || true
